### ISSUE TITLE
telegraf crashes if login/password is incorrect in rabbitmq plugin

### ISSUE THREAD

**Issue by ekini** [influxdb/telegraf#260]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x552006]

goroutine 23 [running]:
github.com/influxdb/telegraf/plugins/rabbitmq.(*RabbitMQ).gatherServer(0xc820143540, 0xc820020ae0, 0x7f60c9322ef0, 0xc820138820, 0x0, 0x0)
	/home/ekini/.gvm/pkgsets/go1.5/global/src/github.com/influxdb/telegraf/plugins/rabbitmq/rabbitmq.go:127 +0x10f6
github.com/influxdb/telegraf/plugins/rabbitmq.(*RabbitMQ).Gather(0xc820143540, 0x7f60c9322ef0, 0xc820138820, 0x0, 0x0)
	/home/ekini/.gvm/pkgsets/go1.5/global/src/github.com/influxdb/telegraf/plugins/rabbitmq/rabbitmq.go:105 +0x13e
github.com/influxdb/telegraf.(*Agent).crankParallel.func1(0xc8201ba210, 0xc82013ba40, 0xc8200214a0, 0xc820136ff0)
	/home/ekini/.gvm/pkgsets/go1.5/global/src/github.com/influxdb/telegraf/agent.go:198 +0x1d5
created by github.com/influxdb/telegraf.(*Agent).crankParallel
	/home/ekini/.gvm/pkgsets/go1.5/global/src/github.com/influxdb/telegraf/agent.go:203 +0x89a
```

**Comment by ekini** [comment]
The commit above fixes the crash for me. Can anyone test?

**Comment by sparrc** [comment]
That looks OK to me, can you submit a PR?
